---
- hosts: webservers
  become: true
  tasks:
   - name: "Instalar httpd"
     yum:
       name: httpd
   - name: "know hostname"
     shell: "echo $HOSTNAME"
     register: print_hostname
   - name: "Configurar httpd"
     template:
       src: templates/index.j2
       dest: /var/www/html/index.html
       owner: root
       group: wheel
       mode: '0644'
   - name: "empezar httpd"
     service:
      name: httpd
      state: restarted
      enabled: yes
